export const CHANGE_EDITOR_CONTENT = 'CHANGE_EDITOR_CONTENT';
export const CHANGE_EDITOR_CSS = 'CHANGE_EDITOR_CSS';
export const CHANGE_EDITOR_FILENAME = 'CHANGE_EDITOR_FILENAME';
export const CHANGE_WIDTH = 'CHANGE_WIDTH';
export const LOAD_SAMPLE_SUCCESS = 'LOAD_SAMPLE_SUCCESS';
